In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
learning_rate=0.1
tf.set_random_seed(0)
np.random.seed(0)

In [3]:
x_data=[[0,0], [0,1], [1,0], [1,1] ]
y_data=[[0], [1], [1], [0] ]

In [4]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [5]:
#layer1 : 보내는쪽(입력층x1,x2)->은닉층1
W1 = tf.Variable(tf.random_normal([2,5], name='weight1'))
b1 = tf.Variable(tf.random_normal([5]),name='bias1' )

In [6]:
layer1 = tf.sigmoid(tf.matmul(X,W1) +b1)

In [7]:
#layer2 : 보내는쪽(은닉층1)->은닉층2
W2 = tf.Variable(tf.random_normal([5,5], name='weight2'))
b2 = tf.Variable(tf.random_normal([5]),name='bias2' )

In [8]:
layer2 = tf.sigmoid(tf.matmul(X,W1) +b2)

In [9]:
#layer3 : 보내는쪽(은닉층2)->은닉층3
W3 = tf.Variable(tf.random_normal([5,5], name='weight3'))
b3 = tf.Variable(tf.random_normal([5]),name='bias3' )

In [10]:
layer3 = tf.sigmoid(tf.matmul(X,W1) +b3)

In [11]:
#layer4 : 보내는쪽(은닉층2)->은닉층3
W4 = tf.Variable(tf.random_normal([5,5], name='weight4'))
b4 = tf.Variable(tf.random_normal([5]),name='bias4' )

In [12]:
layer4 = tf.sigmoid(tf.matmul(X,W1) +b4)

In [13]:
#layer5 : 보내는쪽(은닉층3)->출력층y(y층은 1개 노드만 있는 것으로실시)
W5 = tf.Variable(tf.random_normal([5,1], name='weight3'))
b5 = tf.Variable(tf.random_normal([1]),name='bias3' )

In [14]:
layer3 = tf.sigmoid(tf.matmul(X,W1) +b5)

In [15]:
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) +b2)

In [16]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1-hypothesis) )
train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32 )
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32 ))

In [17]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y:y_data})
        if step % 100 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y:y_data }) , sess.run(W2) )
            
    h,c,a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print("\n Hypothesis: \n", h, "\nCorrect : \n", c, "\nAccuracy : \n", a )

0 0.8985588 [[ 0.09167089  0.72692066  0.29150155 -1.611915    1.8532495 ]
 [ 0.60666865 -0.5069711  -0.0751102  -0.22473948 -0.38912082]
 [ 0.941981    1.3763018   2.0310912  -0.57708335  0.00443773]
 [-0.95060515  1.0431359  -0.82495636 -0.47150165  1.1172558 ]
 [-2.5245955  -0.93936896  2.0173376   0.34749538 -1.2782866 ]]
100 0.7239205 [[ 0.42300585  0.67876416  0.3450199  -1.4413863   1.6427432 ]
 [ 1.0742652  -0.546721    0.04855544  0.03151921 -0.662882  ]
 [ 0.9804381   1.3174065   1.969931   -0.5832937  -0.07751916]
 [-0.51185465  0.9790777  -0.751436   -0.24614507  0.83634895]
 [-2.3892968  -0.9829441   1.988557    0.4009319  -1.3780658 ]]
200 0.70886815 [[ 0.5080125   0.66860765  0.36094883 -1.4088742   1.5964447 ]
 [ 1.2038954  -0.535551    0.12152471  0.09974049 -0.71582335]
 [ 0.9749377   1.2708373   1.9084401  -0.6137229  -0.12202034]
 [-0.39771518  0.9647287  -0.7253792  -0.20226355  0.7698455 ]
 [-2.3577604  -1.013115    1.9447001   0.39414775 -1.4117794 ]]
300 0.70486

2900 0.6102269 [[ 0.7054178   0.68180984  0.23047481 -1.3830466   1.6350191 ]
 [ 1.4092325   0.08115213  1.2103868   0.633507   -0.20664288]
 [ 0.8494338   0.84168255  1.1895789  -0.9902305  -0.47178897]
 [-0.46765092  0.8371346  -0.8575818  -0.3523553   0.64176446]
 [-2.9554238  -2.2694533   0.02752587 -0.79873276 -2.5264251 ]]
3000 0.6039889 [[ 0.7288126   0.6939816   0.22930793 -1.37149     1.6484455 ]
 [ 1.4161506   0.10568672  1.2545558   0.65518177 -0.1813782 ]
 [ 0.85695916  0.8420477   1.1815101  -0.9896859  -0.47080308]
 [-0.46873873  0.8333904  -0.86572206 -0.35957617  0.63965   ]
 [-2.9861622  -2.3330073  -0.0758778  -0.8656816  -2.587821  ]]
3100 0.5977224 [[ 0.75399405  0.70774585  0.2296207  -1.3580363   1.663283  ]
 [ 1.4222819   0.129458    1.2984135   0.676308   -0.15660626]
 [ 0.8650416   0.84326106  1.1745875  -0.9882062  -0.46906856]
 [-0.470116    0.8294543  -0.8737301  -0.36685237  0.63733244]
 [-3.0166976  -2.3964097  -0.17948955 -0.9326379  -2.6494644 ]]
3200 0.

5500 0.452715 [[ 1.9068577   1.6257304   0.9541689  -0.20772977  2.500633  ]
 [ 1.3884674   0.39119634  1.9347198   0.9529062   0.15723994]
 [ 1.1360397   1.0289494   1.2650242  -0.7327095  -0.29130664]
 [-0.72618425  0.532868   -1.1726595  -0.6418105   0.346751  ]
 [-3.75139    -3.696034   -2.1174145  -2.23777    -4.009417  ]]
5600 0.44405627 [[ 1.9796569   1.693901    1.0228148  -0.115569    2.5598347 ]
 [ 1.381327    0.3904971   1.9430139   0.95418155  0.15890561]
 [ 1.147641    1.0396385   1.2745097  -0.71601886 -0.28121838]
 [-0.750212    0.50772005 -1.195925   -0.66490334  0.3212666 ]
 [-3.785904   -3.743711   -2.1774993  -2.2837033  -4.0612087 ]]
5700 0.43491906 [[ 2.0545373   1.7647924   1.094926   -0.01941007  2.621329  ]
 [ 1.3740166   0.38924855  1.9502233   0.954478    0.16015422]
 [ 1.1590517   1.0502989   1.2840503  -0.69915754 -0.27109995]
 [-0.7751279   0.4816341  -1.2202922  -0.68962     0.29506668]
 [-3.8208997  -3.7912846  -2.2368739  -2.329886   -4.1127195 ]]
5800 0

8300 0.1822835 [[ 4.0607834   3.8248537   3.3530467   2.873399    4.394862  ]
 [ 1.2759422   0.36852723  2.0133336   0.8991447   0.20245227]
 [ 1.3442817   1.2496704   1.4565305  -0.3234772  -0.04944484]
 [-1.4354764  -0.23386252 -1.9565113  -1.5807579  -0.37495023]
 [-4.7720523  -4.957271   -3.5936053  -3.6705873  -5.2836776 ]]
8400 0.17636618 [[ 4.121675    3.8895211   3.426494    2.9636073   4.450881  ]
 [ 1.2773119   0.37166408  2.0171385   0.90258694  0.20658809]
 [ 1.3475176   1.2539585   1.4594139  -0.3137331  -0.04311157]
 [-1.4553115  -0.25601584 -1.9800794  -1.6114483  -0.39556113]
 [-4.8054876  -4.9966254  -3.6371722  -3.7217453  -5.3208137 ]]
8500 0.17074281 [[ 4.1810994   3.9526398   3.4982166   3.0513263   4.505632  ]
 [ 1.2789521   0.3750507   2.0211287   0.90646875  0.21088105]
 [ 1.35058     1.2580783   1.462102   -0.3043111  -0.036906  ]
 [-1.4746754  -0.27766755 -2.0030868  -1.6414475  -0.41575328]
 [-4.8384953  -5.035434   -3.6800056  -3.772329   -5.3573728 ]]
8600 