In [1]:
from numpy import array

In [2]:
docs=["너무 재밌네요", "최고예요", "참 잘만든 영화예요","추천하고 싶은 영화입니다", "한 번 더 보고 싶네요",
     "글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

In [3]:
classes= array([1,1,1,1,1,0,0,0,0,0])

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
token = Tokenizer()

In [6]:
token.fit_on_texts(docs)

In [7]:
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘만든': 5, '영화예요': 6, '추천하고': 7, '싶은': 8, '영화입니다': 9, '한': 10, '번': 11, '더': 12, '보고': 13, '싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [8]:
x = token.texts_to_sequences(docs)
print("\n 리뷰텍스트 토근화 결과 :\n",x)


 리뷰텍스트 토근화 결과 :
 [[1, 2], [3], [4, 5, 6], [7, 8, 9], [10, 11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]


In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
#패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.

In [10]:
padded_x = pad_sequences(x,4)

In [11]:
print("\n패딩 결과 :\n",padded_x)


패딩 결과 :
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 0  4  5  6]
 [ 0  7  8  9]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

print("\n 딥러닝 모델 시작:\n")


 딥러닝 모델 시작:



In [13]:
word_size = len(token.word_index)+1

In [15]:
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid') )
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x,classes,epochs=20)
print("\n Accuracy : %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6960 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6939 - accuracy: 0.4000
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6918 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6897 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6876 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6855 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6834 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6814 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6793 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6772 - accuracy: 0.8000
Epoch 11/20
1/1 [===================